plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'kr.co.kwonshzzang'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2023.0.3")  // 사용할 스프링 클라우드 버전 정의
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.retry:spring-retry'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    // 마이그레이션을 통해 데이터베이스 버전 관리할 수 있는 기능 제공
    implementation 'org.flywaydb:flyway-database-postgresql'
    // 애플리케이션이 PostgreSQL 데이터베이스에 연결할 수 있게 해주는 JDBC 드라이버
    runtimeOnly 'org.postgresql:postgresql'
    // JDBC API와 스프링의 통합을 제공한다. 스프링 프레임워크의 일부로 스프링 데이터 JDBC와 혼동하지 말아야 한다.

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    // IDE에서 자동 완성 및 타입 유효성 검사를 받으려면

    runtimeOnly 'org.springframework:spring-jdbc'
    runtimeOnly 'org.postgresql:r2dbc-postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'org.testcontainers:r2dbc'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        // 스프링 클라우드 의존성 관리를 위한 BOM
    }
}

// 빌드팩을 사용해 OCI 이미지를 빌드하기 위한 스프링 부트 플러그인 작업
bootBuildImage {
    // 빌드할 OCI 이미지의 이름. 이 이름은 그래들의 프로젝트 설정에서 정의한 이름과 같다.
    // 버전 번호를 사용하지 않고 암묵적인 latest 태그를 사용한다.
    imageName = "${project.name}"
    // 이미지에 설치할 JVM 버전. 최신 버전인 자바 17을 사용한다.
    environment = ["BP_JVM_VERSION" : "17.*"]

    // 컨테이너 저장소 연결을 설정하기 위한 섹션
//    docker {
//        // 컨테이너 저장소 인증을 설정하기 위한 섹션. 값은 그래들 속성을 통해 전달된다.
//        publishRegistry {
//            username = project.findProperty("registryUsername")
//            password = project.findProperty("registryToken")
//            url = project.findProperty("registryUrl")
//        }
//    }
}

tasks.named('test') {
    useJUnitPlatform()
}
